version: "3"

services:
  # Caddy web proxy – это веб сервер с автоматической настройкой https
  # Настройки Caddy лежат в Caddyfile. Там необходимо заменить email и доменное имя, на котором
  # будет размещаться ваше приложение
  webproxy:
    image: caddy:2.6.4
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  # Контейнер приложения
  # После того, как запрос от пользователя был обработан в контейнере web proxy он будет
  # перенаправлен в этот контейнер. Данный контейнер будет доступен по адрему http://app:80
  # внутри сети docker.
  app:
    build:
      context: ..
      dockerfile: ./cicd/Dockerfile
    environment:
      - DB_DSN=postgresql://postgres@database:5432/postgres

  # Контейнер базы данных
  # В тестовом приложении база данных не используется, но она может понадобится вам позже
  # Мы не настраиваем БД тут, поэтому у нее будут следующие данные для подключения
  # Адрес: database
  # Порт: 5432
  # Имя суперпользователя: postgres
  # Пароль: *без пароля*
  database:
    image: postgres:15
    ports:
      - 5432:5432  # База данных будет доступна из интернета, не забывайте выставить пароль!
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
